import {
  Callout,
  DocCode,
  DocH1,
  DocH2,
  DocP,
  DocTable,
  Mono,
} from '../../components/doc'

const FULL_CONFIG = `# toris.yaml — generated by "toris init"
# Looked up at $HOME/.toris/toris.yaml, /etc/toris/toris.yaml, ./toris.yaml

control_dsn: "host=localhost port=5432 user=toris dbname=toris_control sslmode=require"

cluster:
  id: "pg-main"
  nodes:
    - id: "node-01"
      host: "pg-primary.example.com"
      port: 5432
    - id: "node-02"
      host: "pg-replica-1.example.com"
      port: 5432

proxy:
  listen_addr: "127.0.0.1:5433"

failover:
  enabled: true
  unhealthy_threshold: "60s"
  replication_outage_threshold: "5m"
  auto_rewind_after_failover: true

backup:
  storage_backend: "fs"        # or "s3" (build with -tags s3)
  base_dir: "/var/lib/toris/backups"
  retention:
    keep_last: 7
    keep_daily: 30
    keep_weekly: 8

metrics:
  listen_addr: "127.0.0.1:9090"`

const S3_CONFIG = `backup:
  storage_backend: "s3"
  s3:
    endpoint: "https://s3.example.com"
    bucket: "toris-backups"
    region: "us-east-1"
    access_key_id: "<id>"
    secret_access_key: "<secret>"`

export function Configuration() {
  return (
    <>
      <DocH1>Configuration</DocH1>
      <DocP>
        Generate a fully commented starter config with{' '}
        <Mono>toris init</Mono>. This page is a condensed reference — the
        generated file remains the authoritative source.
      </DocP>

      <DocH2 id="lookup">Config lookup</DocH2>
      <DocP>
        toris looks for the config file in order:
      </DocP>
      <DocCode
        code={`$HOME/.toris/toris.yaml
/etc/toris/toris.yaml
./toris.yaml`}
        lang="text"
        title="lookup order"
      />
      <Callout tone="warn">
        Config files contain credentials (control DSN, S3 keys).{' '}
        <Mono>toris.yaml</Mono> and <Mono>*.local.yaml</Mono> are gitignored in
        the repository for this reason.
      </Callout>

      <DocH2 id="full-example">Full example</DocH2>
      <DocCode code={FULL_CONFIG} lang="yaml" title="toris.yaml" />

      <DocH2 id="key-fields">Key fields</DocH2>
      <DocTable
        head={['Field', 'Purpose']}
        rows={[
          ['control_dsn', 'Connection to the control database. Required for daemon operation.'],
          ['cluster.id', 'Cluster identifier for the lease and audit namespace.'],
          ['cluster.nodes', 'The nodes toris manages: id, host, port.'],
          ['proxy.listen_addr', 'Where the single-DSN proxy listens (default 127.0.0.1:5433).'],
          ['failover.enabled', 'Master switch for automatic failover.'],
          ['failover.unhealthy_threshold', 'How long a primary must be unhealthy before failover starts.'],
          ['failover.replication_outage_threshold', 'Class A escalation timer for replica connectivity loss.'],
          ['failover.auto_rewind_after_failover', 'Automatically rewind/reseed the demoted primary.'],
          ['backup.storage_backend', 'fs (default) or s3 (build with -tags s3).'],
          ['backup.base_dir', 'Where filesystem backups live.'],
          ['backup.retention', 'Keep-last, keep-daily, and keep-weekly policies.'],
          ['metrics.listen_addr', 'Prometheus /metrics and /healthz.'],
        ]}
      />

      <DocH2 id="s3">S3-compatible storage</DocH2>
      <DocP>
        Object storage requires building toris with the S3 build tag:
      </DocP>
      <DocCode code="go build -tags s3 -o bin/toris ./cmd/toris" lang="bash" title="build" />
      <DocCode code={S3_CONFIG} lang="yaml" title="s3 config" />

      <DocH2 id="validate">Validating</DocH2>
      <DocP>
        <Mono>toris config validate</Mono> reports all problems in one pass, and{' '}
        <Mono>toris doctor</Mono> runs eight environment checks. Exit code 2
        means config validation failed; exit code 3 means a doctor check failed.
      </DocP>
    </>
  )
}
