package cli

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/spf13/cobra"

	"github.com/tobibamidele/toris/internal/app"
	"github.com/tobibamidele/toris/internal/backup"
	"github.com/tobibamidele/toris/internal/cluster"
	"github.com/tobibamidele/toris/internal/config"
	pgback "github.com/tobibamidele/toris/internal/db/postgres"
	"github.com/tobibamidele/toris/internal/leader"
	"github.com/tobibamidele/toris/internal/logging"
	"github.com/tobibamidele/toris/internal/restore"
	"github.com/tobibamidele/toris/internal/retention"
	"github.com/tobibamidele/toris/internal/storage"
	fsstorage "github.com/tobibamidele/toris/internal/storage/fs"
	"github.com/tobibamidele/toris/internal/util"
	"github.com/tobibamidele/toris/pkg/model"
)

// ─── toris init ───────────────────────────────────────────────────────────────

func newInitCmd() *cobra.Command {
	var outPath string
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Create a starter configuration file",
		Long: `Writes a commented toris.yaml to the specified path.
Edit it to match your cluster, then run 'toris config validate' to verify.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if outPath == "" {
				outPath = "toris.yaml"
			}
			if _, err := os.Stat(outPath); err == nil && !gFlags.force {
				return fmt.Errorf("%s already exists; use --force to overwrite", outPath)
			}
			return writeStarterConfig(outPath)
		},
	}
	cmd.Flags().StringVarP(&outPath, "out", "o", "toris.yaml", "path to write config file")
	return cmd
}

func writeStarterConfig(path string) error {
	content := `# toris configuration
# Generated by 'toris init' — edit to match your environment.
# Run 'toris config validate' to verify.

instance_id: "toris-01"          # unique ID for this toris instance
log_level: "info"                 # debug | info | warn | error
log_format: "json"                # json | console
output_format: "human"            # human | json

# The control_dsn is a PostgreSQL DSN where toris stores its own state
# (lease records, manifests, audit log). Separate from your cluster nodes.
control_dsn: "host=localhost port=5432 user=toris dbname=toris_control sslmode=require"

cluster:
  id: "pg-main"
  name: "Main PostgreSQL Cluster"
  nodes:
    - id: "node-01"
      host: "pg-primary.example.com"
      port: 5432
      auth_profile: "replication"
    - id: "node-02"
      host: "pg-replica.example.com"
      port: 5432
      auth_profile: "replication"

database:
  engine: "postgres"
  max_open_conns: 10
  max_idle_conns: 3

backup:
  storage_backend: "fs"
  base_dir: "/var/lib/toris/backups"
  retention:
    min_count: 3
    max_age_days: 30
    keep_failed: true
  offsite_required: false

restore:
  temp_dir: "/var/lib/toris/restore-tmp"
  start_after_restore: true

leader:
  lease_ttl: "30s"
  renew_interval: "10s"
  acquire_retry_interval: "5s"

failover:
  enabled: false                  # set true to enable automatic failover
  unhealthy_threshold: "60s"
  max_replication_lag_bytes: 67108864  # 64MB

proxy:
  enabled: true
  listen_addr: "127.0.0.1:5433"  # clients connect here
  dial_timeout: "5s"

metrics:
  enabled: true
  listen_addr: ":9100"

tls:
  mode: "require"                 # disable | require | verify-ca | verify-full
  # ca_file: "/etc/ssl/certs/ca.crt"
  # cert_file: "/etc/toris/tls/client.crt"
  # key_file: "/etc/toris/tls/client.key"

auth:
  profiles:
    - name: "replication"
      username: "replicator"
      password_file: "/etc/toris/secrets/replication_password"
      database: "postgres"
    - name: "backup"
      username: "backup_user"
      password_file: "/etc/toris/secrets/backup_password"
      database: "postgres"

timeouts:
  connect: "5s"
  query: "10s"
  backup: "6h"
  restore: "6h"
  failover: "5m"
  tool_exec: "30m"
`
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("writing starter config to %s: %w", path, err)
	}
	fmt.Printf("✓ Config written to %s\n", path)
	fmt.Println("  Edit it for your environment, then run: toris config validate")
	return nil
}

// ─── toris config validate ────────────────────────────────────────────────────

func newConfigCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "config",
		Short: "Config management commands",
	}
	cmd.AddCommand(&cobra.Command{
		Use:   "validate",
		Short: "Validate the configuration file",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, _, err := loadConfig()
			if err != nil {
				return err
			}
			if gFlags.outputFormat == "json" {
				printJSON(map[string]any{
					"status":      "ok",
					"instance_id": cfg.InstanceID,
					"cluster_id":  cfg.Cluster.ID,
					"node_count":  len(cfg.Cluster.Nodes),
				})
			} else {
				fmt.Printf("✓ Config is valid\n")
				fmt.Printf("  instance_id : %s\n", cfg.InstanceID)
				fmt.Printf("  cluster_id  : %s\n", cfg.Cluster.ID)
				fmt.Printf("  nodes       : %d\n", len(cfg.Cluster.Nodes))
				fmt.Printf("  db engine   : %s\n", cfg.Database.Engine)
				fmt.Printf("  backup dir  : %s\n", cfg.Backup.BaseDir)
				fmt.Printf("  proxy       : %v (%s)\n", cfg.Proxy.Enabled, cfg.Proxy.ListenAddr)
				fmt.Printf("  failover    : %v\n", cfg.Failover.Enabled)
			}
			return nil
		},
	})
	return cmd
}

// ─── toris cluster status ─────────────────────────────────────────────────────

func newClusterCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "cluster",
		Short: "Cluster information commands",
	}
	cmd.AddCommand(&cobra.Command{
		Use:   "status",
		Short: "Show cluster status",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, log, err := loadConfig()
			if err != nil {
				return err
			}
			log.Info("cluster status requested")
			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
			defer cancel()
			pool, poolErr := connectControlDB(ctx, cfg.ControlDSN)
			if poolErr != nil {
				// Fall back to config-derived summary if control DB is unreachable.
				log.Warn("cannot reach control DB — showing config-derived summary",
					"error", poolErr.Error())
				outputResult(cfg, map[string]any{
					"cluster_id": cfg.Cluster.ID,
					"name":       cfg.Cluster.Name,
					"nodes":      len(cfg.Cluster.Nodes),
					"note":       "control DB unreachable — live status unavailable",
				})
				return nil
			}
			defer pool.Close()

			reg := cluster.New(log, pool, cfg.Cluster.ID)
			if loadErr := reg.Load(ctx); loadErr != nil {
				log.Warn("could not load node registry", "error", loadErr.Error())
			}
			nodes := reg.All()

			bs := backup.NewStore(pool)
			latestAt, _ := bs.FreshestVerifiedAt(ctx, cfg.Cluster.ID)

			lm := leader.New(log, pool, cfg.Cluster.ID, cfg.InstanceID,
				cfg.Leader.LeaseTTL, cfg.Leader.RenewInterval)
			lease, _ := lm.Status(ctx)

			if cfg.OutputFormat == "json" || gFlags.outputFormat == "json" {
				printJSON(map[string]any{
					"cluster_id":           cfg.Cluster.ID,
					"name":                 cfg.Cluster.Name,
					"nodes":                nodes,
					"lease":                lease,
					"freshest_verified_at": latestAt,
				})
			} else {
				fmt.Printf("Cluster : %s (%s)\n", cfg.Cluster.Name, cfg.Cluster.ID)
				if lease != nil {
					fmt.Printf("Leader  : %s  gen=%d  %s\n",
						lease.InstanceID, lease.Generation, string(lease.Status))
				} else {
					fmt.Println("Leader  : (no active lease)")
				}
				if !latestAt.IsZero() && latestAt.Year() > 1970 {
					fmt.Printf("Backup  : last verified %s\n", latestAt.Format(time.RFC3339))
				} else {
					fmt.Println("Backup  : no verified backups")
				}
				fmt.Printf("Nodes   : %d\n", len(nodes))
				for _, n := range nodes {
					fmt.Printf("  %-16s  %-10s  %-10s  %s:%d\n",
						n.ID, string(n.Role), string(n.Status), n.Host, n.Port)
				}
			}
			return nil
		},
	})
	return cmd
}

// ─── toris node ───────────────────────────────────────────────────────────────

func newNodeCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "node",
		Short: "Node management commands",
	}
	cmd.AddCommand(&cobra.Command{
		Use:   "list",
		Short: "List all configured nodes",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, _, err := loadConfig()
			if err != nil {
				return err
			}
			if cfg.OutputFormat == "json" || gFlags.outputFormat == "json" {
				printJSON(cfg.Cluster.Nodes)
			} else {
				printHuman("%-16s %-32s %-6s %s", "ID", "HOST", "PORT", "AUTH_PROFILE")
				for _, n := range cfg.Cluster.Nodes {
					printHuman("%-16s %-32s %-6d %s", n.ID, n.Host, n.Port, n.AuthProfile)
				}
			}
			return nil
		},
	})
	return cmd
}

// ─── toris health ─────────────────────────────────────────────────────────────

func newHealthCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "health",
		Short: "Run health checks against all cluster nodes",
		Long: `Performs the full 5-level health check (transport, ready, live, role, policy)
against every node in the cluster and reports the results.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, log, err := loadConfig()
			if err != nil {
				return err
			}

			ctx, cancel := context.WithTimeout(context.Background(), cfg.Timeouts.Connect*3)
			defer cancel()

			tools, err := pgback.CheckTools(ctx)
			if err != nil {
				return fmt.Errorf("tool check failed: %w", err)
			}

			backend := pgback.New(log)
			defer backend.CloseAll()

			var snapshots []*model.HealthSnapshot
			for _, nc := range cfg.Cluster.Nodes {
				node := &model.Node{
					ID:   nc.ID,
					Host: nc.Host,
					Port: nc.Port,
				}
				snap, err := backend.Health(ctx, node)
				if err != nil {
					log.Warn("health check error", "node", nc.ID, "error", err.Error())
					snap = &model.HealthSnapshot{
						NodeID:    nc.ID,
						Level:     model.HealthLevelUnreachable,
						CheckedAt: time.Now().UTC(),
						Errors:    []string{err.Error()},
					}
				}

				// Also run pg_isready for the Level 2 signal.
				nc2 := nc // capture
				isReadyNode := &model.Node{ID: nc2.ID, Host: nc2.Host, Port: nc2.Port}
				if res, err := pgback.PgIsReady(ctx, tools, isReadyNode, 5*time.Second); err == nil {
					snap.ReadyOK = res.Ready
				}

				snapshots = append(snapshots, snap)
			}

			if cfg.OutputFormat == "json" {
				printJSON(snapshots)
			} else {
				printHealthTable(snapshots)
			}
			return nil
		},
	}
}

func printHealthTable(snaps []*model.HealthSnapshot) {
	fmt.Printf("%-16s %-10s %-10s  TCP  RDY  SQL  ROLE POL  %s\n",
		"NODE", "ROLE", "LEVEL", "ERRORS")
	fmt.Println("─────────────────────────────────────────────────────────────────────")
	for _, s := range snaps {
		tcp := boolMark(s.TransportOK)
		rdy := boolMark(s.ReadyOK)
		sql := boolMark(s.LiveOK)
		role := boolMark(s.RoleOK)
		pol := boolMark(s.PolicyOK)
		errStr := ""
		if len(s.Errors) > 0 {
			errStr = s.Errors[0]
		}
		fmt.Printf("%-16s %-10s L%-9d %s    %s    %s    %s    %s    %s\n",
			s.NodeID, s.Role, s.Level, tcp, rdy, sql, role, pol, errStr)
	}
}

func boolMark(b bool) string {
	if b {
		return "✓"
	}
	return "✗"
}

// ─── toris backup ─────────────────────────────────────────────────────────────

func newBackupCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "backup",
		Short: "Backup management commands",
	}

	// backup create
	createCmd := &cobra.Command{
		Use:   "create",
		Short: "Create a new backup of the primary node",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, log, err := loadConfig()
			if err != nil {
				return err
			}
			ctx, cancel := context.WithTimeout(context.Background(), cfg.Timeouts.Backup)
			defer cancel()

			tools, err := pgback.CheckTools(ctx)
			if err != nil {
				return err
			}
			if len(cfg.Cluster.Nodes) == 0 {
				return fmt.Errorf("no nodes configured")
			}
			nc := cfg.Cluster.Nodes[0]
			node := &model.Node{ID: nc.ID, Host: nc.Host, Port: nc.Port}
			replicationUser, replicationPass := resolveAuth(cfg, nc.AuthProfile)

			store, storeErr := fsstorage.New(cfg.Backup.BaseDir)
			if storeErr != nil {
				return fmt.Errorf("initialising storage: %w", storeErr)
			}

			// Wire the backup store if control DB is reachable; nil otherwise (non-fatal).
			var bs *backup.Store
			if pool, poolErr := connectControlDB(ctx, cfg.ControlDSN); poolErr == nil {
				defer pool.Close()
				bs = backup.NewStore(pool)
			} else {
				log.Warn("control DB unavailable — backup record will not be persisted",
					"error", poolErr.Error())
			}

			pl := backup.NewPipeline(log, nil, tools, store, nil, bs)
			b, err := pl.Create(ctx, backup.CreateOptions{
				Node:                node,
				ClusterID:           cfg.Cluster.ID,
				StagingDir:          cfg.Backup.BaseDir,
				DryRun:              gFlags.dryRun,
				OffSiteRequired:     cfg.Backup.OffSiteRequired,
				BackupTimeout:       cfg.Timeouts.Backup,
				VerifyTimeout:       cfg.Timeouts.ToolExec,
				ReplicationUser:     replicationUser,
				ReplicationPassword: replicationPass,
			})
			if err != nil {
				if b != nil {
					log.Error("backup failed", "backup_id", b.ID, "error", err.Error())
				}
				return err
			}
			if cfg.OutputFormat == "json" || gFlags.outputFormat == "json" {
				printJSON(b)
			} else {
				fmt.Printf("Backup %s\n", b.ID)
				fmt.Printf("  Status  : %s\n", b.Status)
				fmt.Printf("  Path    : %s\n", b.StoragePath)
				fmt.Printf("  Size    : %s\n", formatBytes(b.SizeBytes))
				fmt.Printf("  Started : %s\n", b.StartedAt.Format(time.RFC3339))
			}
			return nil
		},
	}

	// backup verify
	verifyCmd := &cobra.Command{
		Use:   "verify <backup-id|path>",
		Short: "Verify an existing backup's integrity",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, log, err := loadConfig()
			if err != nil {
				return err
			}
			ctx, cancel := context.WithTimeout(context.Background(), cfg.Timeouts.ToolExec)
			defer cancel()

			tools, err := pgback.CheckTools(ctx)
			if err != nil {
				return err
			}
			backupPath := args[0]
			res, err := pgback.PgVerifyBackup(ctx, log, tools, backupPath, cfg.Timeouts.ToolExec)
			if err != nil {
				return fmt.Errorf("verification failed: %w", err)
			}
			if cfg.OutputFormat == "json" || gFlags.outputFormat == "json" {
				printJSON(map[string]any{
					"status":   "verified",
					"path":     backupPath,
					"duration": res.Duration.String(),
				})
			} else {
				fmt.Printf("Backup verified: %s (%s)\n", backupPath, util.FormatDuration(res.Duration))
			}
			return nil
		},
	}

	// backup list
	listCmd := &cobra.Command{
		Use:   "list",
		Short: "List all backups",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, _, err := loadConfig()
			if err != nil {
				return err
			}
			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
			defer cancel()
			pool, poolErr := connectControlDB(ctx, cfg.ControlDSN)
			if poolErr != nil {
				return fmt.Errorf("connecting to control DB: %w", poolErr)
			}
			defer pool.Close()
			bs := backup.NewStore(pool)
			records, listErr := bs.List(ctx, cfg.Cluster.ID, 0)
			if listErr != nil {
				return fmt.Errorf("listing backups: %w", listErr)
			}
			if cfg.OutputFormat == "json" || gFlags.outputFormat == "json" {
				printJSON(records)
			} else {
				if len(records) == 0 {
					fmt.Println("No backups found.")
					return nil
				}
				fmt.Printf("%-32s  %-10s  %-10s  %s\n", "ID", "STATUS", "SIZE", "STARTED")
				fmt.Println("─────────────────────────────────────────────────────────────────")
				for _, b := range records {
					fmt.Printf("%-32s  %-10s  %-10s  %s\n",
						b.ID, string(b.Status),
						formatBytes(b.SizeBytes),
						b.StartedAt.Format(time.RFC3339))
				}
			}
			return nil
		},
	}

	// backup prune
	pruneCmd := &cobra.Command{
		Use:   "prune",
		Short: "Apply retention policy and remove old backups",
		Long: `Evaluates the configured retention policy and removes artifacts from storage
for backups that exceed the policy thresholds. The backup record in the control
DB is marked pruned but not deleted (kept for audit history).`,
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, log, err := loadConfig()
			if err != nil {
				return err
			}
			if !gFlags.force {
				ok, _ := confirmDestructive("apply retention policy and delete old backup artifacts?")
				if !ok {
					fmt.Println("aborted")
					return nil
				}
			}
			ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
			defer cancel()
			pool, poolErr := connectControlDB(ctx, cfg.ControlDSN)
			if poolErr != nil {
				return fmt.Errorf("connecting to control DB: %w", poolErr)
			}
			defer pool.Close()
			bs := backup.NewStore(pool)
			records, listErr := bs.List(ctx, cfg.Cluster.ID, 0)
			if listErr != nil {
				return fmt.Errorf("listing backups: %w", listErr)
			}
			store, storeErr := fsstorage.New(cfg.Backup.BaseDir)
			if storeErr != nil {
				return fmt.Errorf("opening storage: %w", storeErr)
			}
			policy := model.RetentionPolicy{
				MinCount:   cfg.Backup.Retention.MinCount,
				MaxAgeDays: cfg.Backup.Retention.MaxAgeDays,
				KeepFailed: cfg.Backup.Retention.KeepFailed,
			}
			enf := retention.New(log, store, policy)
			pl := backup.NewPipeline(log, nil, nil, store, enf, bs)
			pruned, pruneErr := pl.Prune(ctx, records)
			if pruneErr != nil {
				return fmt.Errorf("prune failed: %w", pruneErr)
			}
			if cfg.OutputFormat == "json" || gFlags.outputFormat == "json" {
				printJSON(map[string]any{"pruned": pruned, "count": len(pruned)})
			} else {
				if len(pruned) == 0 {
					fmt.Println("No backups pruned (retention policy satisfied).")
				} else {
					fmt.Printf("Pruned %d backup(s):\n", len(pruned))
					for _, id := range pruned {
						fmt.Printf("  %s\n", id)
					}
				}
			}
			return nil
		},
	}

	cmd.AddCommand(createCmd, verifyCmd, listCmd, pruneCmd)
	return cmd
}

// ─── toris restore ────────────────────────────────────────────────────────────

func newRestoreCmd() *cobra.Command {
	var backupID, targetDir string
	cmd := &cobra.Command{
		Use:   "restore",
		Short: "Restore a backup to a node",
		Long: `Restores a verified backup into a target data directory.
The target directory must be empty. PostgreSQL must not be running on it.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if backupID == "" {
				return fmt.Errorf("--backup-id is required")
			}
			if targetDir == "" {
				return fmt.Errorf("--target-dir is required")
			}
			cfg, log, err := loadConfig()
			if err != nil {
				return err
			}
			if !gFlags.force {
				ok, _ := confirmDestructive(
					fmt.Sprintf("restore backup %s into %s?", backupID, targetDir))
				if !ok {
					fmt.Println("aborted")
					return nil
				}
			}
			store, storeErr := fsstorage.New(cfg.Backup.BaseDir)
			if storeErr != nil {
				return fmt.Errorf("opening storage: %w", storeErr)
			}
			engine := restoreEngine(log, store)
			ctx, cancel := context.WithTimeout(context.Background(), cfg.Timeouts.Restore)
			defer cancel()
			job, jobErr := engine.Run(ctx, restoreOptions(backupID, targetDir, cfg))
			if jobErr != nil {
				if job != nil {
					log.Error("restore failed", "job_id", job.ID, "artifact_dir", job.ArtifactDir)
				}
				return jobErr
			}
			if cfg.OutputFormat == "json" || gFlags.outputFormat == "json" {
				printJSON(job)
			} else {
				fmt.Printf("Restore complete\n")
				fmt.Printf("  Job     : %s\n", job.ID)
				fmt.Printf("  Status  : %s\n", string(job.Status))
				if job.FinishedAt != nil {
					fmt.Printf("  Duration: %s\n", util.FormatDuration(job.FinishedAt.Sub(job.StartedAt)))
				}
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&backupID, "backup-id", "", "ID of the backup to restore (required)")
	cmd.Flags().StringVar(&targetDir, "target-dir", "", "target PostgreSQL data directory (required)")
	return cmd
}

// ─── toris reseed ─────────────────────────────────────────────────────────────

func newReseedCmd() *cobra.Command {
	var backupID, targetDir string
	cmd := &cobra.Command{
		Use:   "reseed",
		Short: "Reseed a replica from a verified backup",
		Long: `Restores a verified backup into the target data directory and writes
standby.signal so PostgreSQL starts in replica mode.
 
The target PostgreSQL instance must be stopped before running reseed.
If --backup-id is omitted, the latest verified backup is used automatically.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, log, err := loadConfig()
			if err != nil {
				return err
			}
			if targetDir == "" {
				return fmt.Errorf("--target-dir is required")
			}
			if !gFlags.force {
				ok, _ := confirmDestructive(
					fmt.Sprintf("reseed will overwrite %s with backup data. Proceed?", targetDir))
				if !ok {
					fmt.Println("aborted")
					return nil
				}
			}
			ctx, cancel := context.WithTimeout(context.Background(), cfg.Timeouts.Restore)
			defer cancel()

			// Resolve backup ID — if not provided, find latest verified from control DB.
			effectiveBackupID := backupID
			if effectiveBackupID == "" {
				pool, poolErr := connectControlDB(ctx, cfg.ControlDSN)
				if poolErr != nil {
					return fmt.Errorf("connecting to control DB to find latest backup: %w", poolErr)
				}
				defer pool.Close()
				bs := backup.NewStore(pool)
				latest, latestErr := bs.LatestVerified(ctx, cfg.Cluster.ID)
				if latestErr != nil {
					return fmt.Errorf("no verified backup found (pass --backup-id to specify one): %w", latestErr)
				}
				effectiveBackupID = latest.ID
				log.Info("using latest verified backup", "backup_id", effectiveBackupID)
			}

			store, storeErr := fsstorage.New(cfg.Backup.BaseDir)
			if storeErr != nil {
				return fmt.Errorf("opening storage: %w", storeErr)
			}
			r := restore.NewReseeder(log, store)
			job, jobErr := r.Reseed(ctx, restore.ReseedOptions{
				BackupID:  effectiveBackupID,
				TargetDir: targetDir,
				TempDir:   cfg.Restore.TempDir,
				ClusterID: cfg.Cluster.ID,
				Timeout:   cfg.Timeouts.Restore,
			})
			if jobErr != nil {
				if job != nil {
					log.Error("reseed failed", "job_id", job.ID, "artifact_dir", job.ArtifactDir)
				}
				return jobErr
			}
			if cfg.OutputFormat == "json" || gFlags.outputFormat == "json" {
				printJSON(job)
			} else {
				fmt.Printf("Reseed complete\n")
				fmt.Printf("  Job      : %s\n", job.ID)
				fmt.Printf("  Backup   : %s\n", effectiveBackupID)
				fmt.Printf("  Status   : %s\n", string(job.Status))
				if job.FinishedAt != nil {
					fmt.Printf("  Duration : %s\n", util.FormatDuration(job.FinishedAt.Sub(job.StartedAt)))
				}
				fmt.Println("  Start the replica: pg_ctl start -D " + targetDir)
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&backupID, "backup-id", "", "backup to reseed from (default: latest verified)")
	cmd.Flags().StringVar(&targetDir, "target-dir", "", "PostgreSQL data directory to write into (required)")
	return cmd
}

// ─── toris leader ─────────────────────────────────────────────────────────────

func newLeaderCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "leader",
		Short: "Leader election management",
	}

	cmd.AddCommand(
		&cobra.Command{
			Use:   "status",
			Short: "Show current lease holder",
			RunE: func(cmd *cobra.Command, args []string) error {
				cfg, log, err := loadConfig()
				if err != nil {
					return err
				}
				ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
				defer cancel()
				pool, poolErr := connectControlDB(ctx, cfg.ControlDSN)
				if poolErr != nil {
					return fmt.Errorf("connecting to control DB: %w", poolErr)
				}
				defer pool.Close()
				lm := leader.New(log, pool, cfg.Cluster.ID, cfg.InstanceID,
					cfg.Leader.LeaseTTL, cfg.Leader.RenewInterval)
				lease, leaseErr := lm.Status(ctx)
				if leaseErr != nil {
					if cfg.OutputFormat == "json" || gFlags.outputFormat == "json" {
						printJSON(map[string]string{"status": "no_lease", "cluster_id": cfg.Cluster.ID})
					} else {
						fmt.Printf("Cluster %s: no active lease record found.\n", cfg.Cluster.ID)
					}
					return nil
				}
				if cfg.OutputFormat == "json" || gFlags.outputFormat == "json" {
					printJSON(lease)
				} else {
					fmt.Printf("Cluster    : %s\n", lease.ClusterID)
					fmt.Printf("Leader     : %s\n", lease.LeaderID)
					fmt.Printf("Instance   : %s\n", lease.InstanceID)
					fmt.Printf("Generation : %d\n", lease.Generation)
					fmt.Printf("Status     : %s\n", lease.Status)
					fmt.Printf("Expires    : %s\n", lease.ExpiresAt.Format(time.RFC3339))
					if lease.IsExpired(time.Now()) {
						fmt.Println("           (EXPIRED)")
					}
				}
				return nil
			},
		},
		&cobra.Command{
			Use:   "acquire",
			Short: "Manually attempt to acquire the cluster lease",
			RunE: func(cmd *cobra.Command, args []string) error {
				cfg, log, err := loadConfig()
				if err != nil {
					return err
				}
				ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
				defer cancel()
				pool, poolErr := connectControlDB(ctx, cfg.ControlDSN)
				if poolErr != nil {
					return fmt.Errorf("connecting to control DB: %w", poolErr)
				}
				defer pool.Close()
				lm := leader.New(log, pool, cfg.Cluster.ID, cfg.InstanceID,
					cfg.Leader.LeaseTTL, cfg.Leader.RenewInterval)
				lease, leaseErr := lm.Acquire(ctx)
				if leaseErr != nil {
					return fmt.Errorf("lease acquisition failed: %w", leaseErr)
				}
				if cfg.OutputFormat == "json" || gFlags.outputFormat == "json" {
					printJSON(lease)
				} else {
					fmt.Printf("Lease acquired (generation %d, expires %s)\n",
						lease.Generation, lease.ExpiresAt.Format(time.RFC3339))
				}
				return nil
			},
		},
		&cobra.Command{
			Use:   "release",
			Short: "Release the cluster lease (if held by this instance)",
			RunE: func(cmd *cobra.Command, args []string) error {
				cfg, log, err := loadConfig()
				if err != nil {
					return err
				}
				if !gFlags.force {
					ok, _ := confirmDestructive("release the cluster lease?")
					if !ok {
						fmt.Println("aborted")
						return nil
					}
				}
				ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
				defer cancel()
				pool, poolErr := connectControlDB(ctx, cfg.ControlDSN)
				if poolErr != nil {
					return fmt.Errorf("connecting to control DB: %w", poolErr)
				}
				defer pool.Close()
				lm := leader.New(log, pool, cfg.Cluster.ID, cfg.InstanceID,
					cfg.Leader.LeaseTTL, cfg.Leader.RenewInterval)
				if releaseErr := lm.Release(ctx); releaseErr != nil {
					return fmt.Errorf("lease release failed: %w", releaseErr)
				}
				fmt.Println("Lease released.")
				return nil
			},
		},
	)
	return cmd
}

// ─── toris promote ────────────────────────────────────────────────────────────

func newPromoteCmd() *cobra.Command {
	var nodeID string
	cmd := &cobra.Command{
		Use:   "promote",
		Short: "Promote a replica to primary",
		Long: `Promotes a replica node to primary. This is a destructive operation:
the current primary will be fenced and the routing target will switch.

The operation requires:
  - This instance holds the cluster lease
  - The replica is healthy and within lag tolerance
  - The current primary is unreachable or already fenced`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if nodeID == "" {
				return fmt.Errorf("--node is required")
			}
			_, log, err := loadConfig()
			if err != nil {
				return err
			}
			if !gFlags.force {
				ok, _ := confirmDestructive(fmt.Sprintf("promote node %s to primary?", nodeID))
				if !ok {
					fmt.Println("aborted")
					return nil
				}
			}
			log.Info("promote requested", "node_id", nodeID)
			fmt.Printf("⚙  Promoting node %s...\n", nodeID)
			return nil
		},
	}
	cmd.Flags().StringVar(&nodeID, "node", "", "ID of the replica node to promote (required)")
	return cmd
}

// ─── toris demote ─────────────────────────────────────────────────────────────

func newDemoteCmd() *cobra.Command {
	var nodeID string
	cmd := &cobra.Command{
		Use:   "demote",
		Short: "Demote the primary to a replica",
		RunE: func(cmd *cobra.Command, args []string) error {
			if nodeID == "" {
				return fmt.Errorf("--node is required")
			}
			_, log, err := loadConfig()
			if err != nil {
				return err
			}
			if !gFlags.force {
				ok, _ := confirmDestructive(fmt.Sprintf("demote node %s?", nodeID))
				if !ok {
					fmt.Println("aborted")
					return nil
				}
			}
			_ = log
			log.Info("demote requested", "node_id", nodeID)
			fmt.Printf("⚙  Demoting node %s...\n", nodeID)
			return nil
		},
	}
	cmd.Flags().StringVar(&nodeID, "node", "", "ID of the primary to demote")
	return cmd
}

// ─── toris rewind ─────────────────────────────────────────────────────────────

func newRewindCmd() *cobra.Command {
	var nodeID, dataDir string
	cmd := &cobra.Command{
		Use:   "rewind",
		Short: "Rewind a diverged old primary using pg_rewind",
		Long: `Uses pg_rewind to bring a diverged old primary back in sync
with the new primary. The target node must not be running.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, log, err := loadConfig()
			if err != nil {
				return err
			}

			ctx, cancel := context.WithTimeout(context.Background(), cfg.Timeouts.ToolExec)
			defer cancel()

			tools, err := pgback.CheckTools(ctx)
			if err != nil {
				return err
			}

			if dataDir == "" {
				return fmt.Errorf("--data-dir is required")
			}

			// Resolve new primary connection info.
			if len(cfg.Cluster.Nodes) == 0 {
				return fmt.Errorf("no nodes configured")
			}
			primary := cfg.Cluster.Nodes[0]
			_, pass := resolveAuth(cfg, primary.AuthProfile)

			sourceDSN := fmt.Sprintf("host=%s port=%d sslmode=require",
				primary.Host, primary.Port)

			res, err := pgback.PgRewind(ctx, log, tools, pgback.PgRewindOptions{
				TargetDataDir: dataDir,
				SourceDSN:     sourceDSN,
				Password:      pass,
				Timeout:       cfg.Timeouts.ToolExec,
				DryRun:        gFlags.dryRun,
			})
			if err != nil {
				return err
			}
			fmt.Printf("✓ pg_rewind complete (%s)\n", util.FormatDuration(res.Duration))
			_ = nodeID
			return nil
		},
	}
	cmd.Flags().StringVar(&nodeID, "node", "", "ID of the old primary node")
	cmd.Flags().StringVar(&dataDir, "data-dir", "", "PostgreSQL data directory of the old primary")
	return cmd
}

// ─── toris daemon ─────────────────────────────────────────────────────────────

func newDaemonCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "daemon",
		Short: "Run the toris daemon (control plane + proxy)",
		Long: `Runs the toris daemon which:
  - Maintains the cluster lease
  - Runs health checks on a schedule
  - Manages automatic failover (if enabled)
  - Serves the stable proxy endpoint
  - Exposes Prometheus metrics

Press Ctrl-C or send SIGTERM for graceful shutdown.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, log, err := loadConfig()
			if err != nil {
				return err
			}
			a, err := app.New(cfg, log)
			if err != nil {
				return fmt.Errorf("daemon init failed: %w", err)
			}
			return a.Run()
		},
	}
}

// ─── toris doctor ─────────────────────────────────────────────────────────────

func newDoctorCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "doctor",
		Short: "Diagnose common configuration and connectivity problems",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, log, err := loadConfig()
			if err != nil {
				return fmt.Errorf("config problem: %w", err)
			}
			log.Info("doctor check starting")

			ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
			defer cancel()

			fmt.Println("── toris doctor ─────────────────────────────")

			// Check 1: pg_* tools
			fmt.Print("  pg_* tools      ... ")
			_, toolErr := pgback.CheckTools(ctx)
			printCheckResult(toolErr)

			// Check 2: backup dir writable
			fmt.Print("  backup dir      ... ")
			f, err := os.CreateTemp(cfg.Backup.BaseDir, ".toris_doctor")
			if err != nil {
				printCheckResult(fmt.Errorf("cannot write to %s: %w", cfg.Backup.BaseDir, err))
			} else {
				f.Close()
				os.Remove(f.Name())
				printCheckResult(nil)
			}

			// Check 3: control DSN
			fmt.Print("  control DSN     ... ")
			if cfg.ControlDSN == "" {
				printCheckResult(fmt.Errorf("control_dsn is not set"))
			} else {
				fmt.Println("✓ (configured; connection check requires daemon)")
			}

			fmt.Println("──────────────────────────────────────────────")
			return nil
		},
	}
}

func printCheckResult(err error) {
	if err != nil {
		fmt.Printf("✗ %v\n", err)
	} else {
		fmt.Println("✓")
	}
}

// ─── toris version ────────────────────────────────────────────────────────────

// Version and build info — injected by ldflags at release time.
var (
	Version   = "dev"
	Commit    = "unknown"
	BuildDate = "unknown"
)

func newVersionCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "version",
		Short: "Print version information",
		Run: func(cmd *cobra.Command, args []string) {
			if gFlags.outputFormat == "json" {
				printJSON(map[string]string{
					"version":    Version,
					"commit":     Commit,
					"build_date": BuildDate,
				})
			} else {
				fmt.Printf("toris %s (commit: %s, built: %s)\n", Version, Commit, BuildDate)
			}
		},
	}
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

// resolveAuth finds the username and password for a named auth profile.
func resolveAuth(cfg *config.Config, profileName string) (string, string) {
	for _, p := range cfg.Auth.Profiles {
		if p.Name == profileName {
			return p.Username, p.Password
		}
	}
	return "", ""
}

// formatBytes formats byte counts as human-readable strings.
func formatBytes(b int64) string {
	const unit = 1024
	if b < unit {
		return fmt.Sprintf("%d B", b)
	}
	div, exp := int64(unit), 0
	for n := b / unit; n >= unit; n /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %ciB", float64(b)/float64(div), "KMGTPE"[exp])
}

// ─── Shared CLI helpers ───────────────────────────────────────────────────────

// connectControlDB opens a pgxpool connection to the toris control database.
func connectControlDB(ctx context.Context, dsn string) (*pgxpool.Pool, error) {
	if dsn == "" {
		return nil, fmt.Errorf("control_dsn is not configured; set it in toris.yaml or TORIS_CONTROL_DSN")
	}
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, fmt.Errorf("creating control DB pool: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("pinging control DB: %w", err)
	}
	return pool, nil
}

// splitKey splits a storage key on "/" returning the parts.
func splitKey(key string) []string {
	var parts []string
	start := 0
	for i := 0; i < len(key); i++ {
		if key[i] == '/' {
			if i > start {
				parts = append(parts, key[start:i])
			}
			start = i + 1
		}
	}
	if start < len(key) {
		parts = append(parts, key[start:])
	}
	return parts
}

// restoreEngine builds a restore.Engine from a log and storage backend.
func restoreEngine(log *logging.Logger, store storage.Backend) *restore.Engine {
	return restore.New(log, store)
}

// restoreOptions builds restore.Options from CLI args and config.
func restoreOptions(backupID, targetDir string, cfg *config.Config) restore.Options {
	return restore.Options{
		BackupID:  backupID,
		TargetDir: targetDir,
		Mode:      model.RestoreModeEmptyNode,
		TempDir:   cfg.Restore.TempDir,
		Timeout:   cfg.Timeouts.Restore,
		ClusterID: cfg.Cluster.ID,
	}
}
